name: eval_2d_curated_v2
classic:
- datasets/evals/classic/nuanced_new/cmrxrecon2023_curated_lax.json
- datasets/evals/classic/nuanced_new/cmrxrecon2023_curated_sax.json
- datasets/evals/classic/nuanced_new/cmrxrecon2023_curated_t1.json
- datasets/evals/classic/nuanced_new/cmrxrecon2023_curated_t2.json
- datasets/evals/classic/nuanced_new/fastmri_brain_curated_flair_15t_16-20c.json
- datasets/evals/classic/nuanced_new/fastmri_brain_curated_flair_30t_16c.json
- datasets/evals/classic/nuanced_new/fastmri_brain_curated_t1_15t_16-20c.json
- datasets/evals/classic/nuanced_new/fastmri_brain_curated_t1_30t_16c.json
- datasets/evals/classic/nuanced_new/fastmri_brain_curated_t1post_15t_20c.json
- datasets/evals/classic/nuanced_new/fastmri_brain_curated_t1post_15t_4c.json
- datasets/evals/classic/nuanced_new/fastmri_brain_curated_t1post_30t_16c.json
- datasets/evals/classic/nuanced_new/fastmri_brain_curated_t2_15t_16c.json
- datasets/evals/classic/nuanced_new/fastmri_brain_curated_t2_15t_4c.json
- datasets/evals/classic/nuanced_new/fastmri_brain_curated_t2_30t_16c.json
- datasets/evals/classic/nuanced_new/fastmri_knee_curated_pd_15t.json
- datasets/evals/classic/nuanced_new/fastmri_knee_curated_pd_30t.json
- datasets/evals/classic/nuanced_new/fastmri_knee_curated_pdfs_15t.json
- datasets/evals/classic/nuanced_new/fastmri_knee_curated_pdfs_30t.json
- datasets/evals/classic/nuanced_new/fastmri_prostate_T2_curated_random.json
- datasets/evals/classic/nuanced_new/m4raw_curated_flair.json
- datasets/evals/classic/nuanced_new/m4raw_curated_t1.json
- datasets/evals/classic/nuanced_new/m4raw_curated_t2.json
- datasets/evals/classic/nuanced_new/m4raw_gre_rot_curated_random.json
- datasets/evals/classic/nuanced_new/nyu_2d_curated_ax_t2fs.json
- datasets/evals/classic/nuanced_new/nyu_2d_curated_cor_pd.json
- datasets/evals/classic/nuanced_new/nyu_2d_curated_cor_pdfs.json
- datasets/evals/classic/nuanced_new/nyu_2d_curated_sag_pd.json
- datasets/evals/classic/nuanced_new/nyu_2d_curated_sag_t2fs.json
- datasets/evals/classic/nuanced_new/ocmr_curated_lax_055T.json
- datasets/evals/classic/nuanced_new/ocmr_curated_lax_15T.json
- datasets/evals/classic/nuanced_new/ocmr_curated_lax_30T.json
- datasets/evals/classic/nuanced_new/ocmr_curated_other_055T.json
- datasets/evals/classic/nuanced_new/ocmr_curated_sax_055T.json
- datasets/evals/classic/nuanced_new/ocmr_curated_sax_15T.json
- datasets/evals/classic/nuanced_new/ocmr_curated_sax_30T.json
- datasets/evals/classic/nuanced_new/smurf_curated_abdomen_conventional.json
- datasets/evals/classic/nuanced_new/smurf_curated_abdomen_dixon.json
- datasets/evals/classic/nuanced_new/smurf_curated_abdomen_fatsat.json
- datasets/evals/classic/nuanced_new/smurf_curated_abdomen_watersat.json
- datasets/evals/classic/nuanced_new/smurf_curated_breast_conventional.json
- datasets/evals/classic/nuanced_new/smurf_curated_breast_dixon.json
- datasets/evals/classic/nuanced_new/smurf_curated_breast_fatsat.json
- datasets/evals/classic/nuanced_new/smurf_curated_breast_watersat.json
- datasets/evals/classic/nuanced_new/smurf_curated_knee_conventional.json
- datasets/evals/classic/nuanced_new/smurf_curated_knee_dixon.json
- datasets/evals/classic/nuanced_new/smurf_curated_knee_fatsat.json
- datasets/evals/classic/nuanced_new/smurf_curated_knee_watersat.json
- datasets/evals/classic/nuanced_new/stanford_2d_curated_random.json
pathology: []
