name: data_pool_random_volume_subset_120k_energy+edge_mode_size_max_samples_80000_epochs=30
num_epochs: 30
samples_seen: 2400000
epochs_setup:
  1: datasets/train/data_pool_random_volume_subset_120k_energy+edge_mode_size_max_samples_80000.json
  2: datasets/train/data_pool_random_volume_subset_120k_energy+edge_mode_size_max_samples_80000.json
  3: datasets/train/data_pool_random_volume_subset_120k_energy+edge_mode_size_max_samples_80000.json
  4: datasets/train/data_pool_random_volume_subset_120k_energy+edge_mode_size_max_samples_80000.json
  5: datasets/train/data_pool_random_volume_subset_120k_energy+edge_mode_size_max_samples_80000.json
  6: datasets/train/data_pool_random_volume_subset_120k_energy+edge_mode_size_max_samples_80000.json
  7: datasets/train/data_pool_random_volume_subset_120k_energy+edge_mode_size_max_samples_80000.json
  8: datasets/train/data_pool_random_volume_subset_120k_energy+edge_mode_size_max_samples_80000.json
  9: datasets/train/data_pool_random_volume_subset_120k_energy+edge_mode_size_max_samples_80000.json
  10: datasets/train/data_pool_random_volume_subset_120k_energy+edge_mode_size_max_samples_80000.json
  11: datasets/train/data_pool_random_volume_subset_120k_energy+edge_mode_size_max_samples_80000.json
  12: datasets/train/data_pool_random_volume_subset_120k_energy+edge_mode_size_max_samples_80000.json
  13: datasets/train/data_pool_random_volume_subset_120k_energy+edge_mode_size_max_samples_80000.json
  14: datasets/train/data_pool_random_volume_subset_120k_energy+edge_mode_size_max_samples_80000.json
  15: datasets/train/data_pool_random_volume_subset_120k_energy+edge_mode_size_max_samples_80000.json
  16: datasets/train/data_pool_random_volume_subset_120k_energy+edge_mode_size_max_samples_80000.json
  17: datasets/train/data_pool_random_volume_subset_120k_energy+edge_mode_size_max_samples_80000.json
  18: datasets/train/data_pool_random_volume_subset_120k_energy+edge_mode_size_max_samples_80000.json
  19: datasets/train/data_pool_random_volume_subset_120k_energy+edge_mode_size_max_samples_80000.json
  20: datasets/train/data_pool_random_volume_subset_120k_energy+edge_mode_size_max_samples_80000.json
  21: datasets/train/data_pool_random_volume_subset_120k_energy+edge_mode_size_max_samples_80000.json
  22: datasets/train/data_pool_random_volume_subset_120k_energy+edge_mode_size_max_samples_80000.json
  23: datasets/train/data_pool_random_volume_subset_120k_energy+edge_mode_size_max_samples_80000.json
  24: datasets/train/data_pool_random_volume_subset_120k_energy+edge_mode_size_max_samples_80000.json
  25: datasets/train/data_pool_random_volume_subset_120k_energy+edge_mode_size_max_samples_80000.json
  26: datasets/train/data_pool_random_volume_subset_120k_energy+edge_mode_size_max_samples_80000.json
  27: datasets/train/data_pool_random_volume_subset_120k_energy+edge_mode_size_max_samples_80000.json
  28: datasets/train/data_pool_random_volume_subset_120k_energy+edge_mode_size_max_samples_80000.json
  29: datasets/train/data_pool_random_volume_subset_120k_energy+edge_mode_size_max_samples_80000.json
  30: datasets/train/data_pool_random_volume_subset_120k_energy+edge_mode_size_max_samples_80000.json
